import os
import streamlit as st
from soilquality import check_soil_quality
from irrigation import analyze_irrigation
from crop import analyze_crop_production
from weather import predict_weather

# Page Configuration
st.set_page_config(
    page_title="Smart Agri DSS",
    page_icon="🌾",
    layout="wide"
)

def main():
    os.makedirs('outputs', exist_ok=True)
    dataset = 'Smartagri/datasets/Crop_recommendation.csv'
    
    st.title("🌾 Smart Farming Decision Support System")
    st.caption("SIH 2026 Prototype — Multi-Module Agricultural Analytics Engine")
    st.divider()

    # Sidebar Options
    st.sidebar.header("Location & Settings")
    lat = st.sidebar.number_input("Latitude", value=28.6139, format="%.4f")
    lon = st.sidebar.number_input("Longitude", value=77.2090, format="%.4f")
    location = st.sidebar.text_input("Location Name", value="Noida, Uttar Pradesh")
    
    # Model Execution & Spinner
    with st.spinner("Executing ML Models & Fetching Weather Data..."):
        soil_model, soil_acc = check_soil_quality(dataset)
        irr_model, irr_acc = analyze_irrigation(dataset)
        crop_model, crop_acc = analyze_crop_production(dataset)
        weather_data = predict_weather(
            latitude=lat,
            longitude=lon,
            location_name=location
        )

    st.success("✅ All ML modules executed successfully!")

    # Top Metric Overview Cards
    st.subheader("📊 System Summary & Model Performance")
    col1, col2, col3, col4 = st.columns(4)
    
    col1.metric("Soil Quality Model", f"{soil_acc * 100:.2f}%")
    col2.metric("Irrigation Model", f"{irr_acc * 100:.2f}%")
    col3.metric("Crop Production Model", f"{crop_acc * 100:.2f}%")
    col4.metric("Weather Status", "Fetched Live")

    st.divider()

    # Tabbed Interface for Detailed Module Details
    tab1, tab2, tab3, tab4 = st.tabs(["🌱 Soil Quality", "💧 Irrigation", "🌾 Crop Analysis", "🌤️ Weather Forecast"])

    with tab1:
        st.subheader("Soil Quality Results")
        st.write(soil_model)

    with tab2:
        st.subheader("Irrigation Analysis")
        st.write(irr_model)

    with tab3:
        st.subheader("Crop Production Analysis")
        st.write(crop_model)

    with tab4:
        st.subheader(f"Weather Forecast for {location}")
        st.json(weather_data) if isinstance(weather_data, dict) else st.write(weather_data)

    st.info("💡 Note: Output charts generated by models are saved in the `/outputs` directory.")

if __name__ == "__main__":
    main()    
